package com.zanox.coreservice.vmware.service.rest;

import javax.ws.rs.ApplicationPath;
import javax.ws.rs.core.Application;
import java.util.Set;

/**
 * Created with IntelliJ IDEA.
 * User: sascha
 * Date: 25.06.13
 * Time: 12:48
 * To change this template use File | Settings | File Templates.
 */
@ApplicationPath("/rest")
public class JaxRsActivator extends Application {

    @Override
    public Set<Class<?>> getClasses() {
        Set<Class<?>> resources = new java.util.HashSet<Class<?>>();
        addRestResourceClasses(resources);
        return resources;
    }

    /**
     * Do not modify addRestResourceClasses() method.
     * It is automatically re-generated by NetBeans REST support to populate
     * given list with all resources defined in the project.
     */
    private void addRestResourceClasses(Set<Class<?>> resources) {
        resources.add(com.zanox.coreservice.vmware.service.rest.VMWareService.class);
    }
}
